### ISSUE TITLE
Thank you for these! 

### ISSUE THREAD

**Issue by kot0005** [nvigneux/Helldivers-2-Stratagems-icons-svg#1]
Thank you for making these, Very helpful to 3D print them. Is there a way to include everythign in 1 File so i dont have to download each one indivudially ?!

How did you make these ?

Again great work!! thank you.

Hopefully more coming soon.

**Comment by nvigneux** [comment]
Hello, 

I don't have a solution for include everything in one file but you can actually download the entire set by clicking on "Code" and then selecting "Download ZIP". That should give you all the icons in one file for easier access.
![Screenshot from 2024-03-05 10-34-38](https://github.com/nvigneux/Helldivers-2-Stratagems-icons-svg/assets/10993891/39f99c8b-f56c-4554-80e5-5fd43d3f037e)


Feel free to share some photos or details. I'm curious to see how they turn out.

I'm glad you're enjoying the icons! If you have any other questions or need further assistance, feel free to ask. 
Thanks for your support!
