### ISSUE TITLE
Simply great work

### ISSUE THREAD

**Issue by Noloxs** [nvigneux/Helldivers-2-Stratagems-icons-svg#10]
This was exactly what I was needed for my macro program.

So I took your advice and used your icons for my own application.
https://github.com/Noloxs/hell_snake

**Comment by nvigneux** [comment]
Thank you for the feedback ! I'm really glad to hear that !
Happy coding! 🚀

**Comment by nvigneux** [comment]
Thank you, I'm glad it can be useful to other people
