### ISSUE TITLE
Could a placeholder stratagem icon be made?

### ISSUE THREAD

**Issue by Noloxs** [nvigneux/Helldivers-2-Stratagems-icons-svg#13]
I was wondering if a placeholder icon could be made for use with new stratagems were to correct icon haven't been made yet?

A suggestion could be something that incorporated the notorious pink question mark:  

![question](https://github.com/nvigneux/Helldivers-2-Stratagems-icons-svg/assets/5433562/e0883249-0193-4949-961f-da27adf1321b)

**Comment by nvigneux** [comment]
Hey,
I see what you mean, but the icons should be available on time. I already have the SVGs ready for some future additions. 
I add them as soon as I have a moment after they are released in the game with their associated code.
