### ISSUE TITLE
Possibility to add the new nuclear drill (can't remember the name) from the new mission type?

### ISSUE THREAD

**Issue by airjairj** [nvigneux/Helldivers-2-Stratagems-icons-svg#14]
If you haven't played in the last few days a new terminid mission was added, and with it a new stratagem, it drills into nests, then nukes them. Can't remember the name but i'm sure it's a 100% new stratagem with a new code

**Comment by nvigneux** [comment]
Hello, it seems to be the same icon as Prospecting Drill ?

https://raw.githubusercontent.com/nvigneux/Helldivers-2-Stratagems-icons-svg/master/General%20Stratagems/Prospecting%20Drill.svg

**Comment by airjairj** [comment]
Yes it is, it only has a different code. My bad.

**Comment by airjairj** [comment]
Yes it is, it only has a different code. My bad.
