### ISSUE TITLE
Missing icons for WASP and Gas mines

### ISSUE THREAD

**Issue by Noloxs** [nvigneux/Helldivers-2-Stratagems-icons-svg#18]
I know that these stratagems aren't currently permanently available, but we still implement them in our macro tool.

Are these icons that you consider making or do you only focus on generally available stratagems?

**Comment by nvigneux** [comment]
I currently focus on creating icons only for stratagems that are permanently available. 
However, in most cases, the icons for limited-time stratagems are already finished and simply waiting for their official release.

That said, I understand how useful it could be to have access to these icons even before their general availability. I’ll consider finding a way to display them in a separate section or implement another solution to make them accessible while keeping them distinct from the permanent ones.

**Comment by Noloxs** [comment]
That would be awesome if you could make that possible.
We really do appreciate the work you do!

**Comment by nvigneux** [comment]
The icons for the WASP and Gas mines are now available in the repository under the [`_Experimental Stratagems`](https://github.com/nvigneux/Helldivers-2-Stratagems-icons-svg?tab=readme-ov-file#experimental-stratagems) folder.
