### ISSUE TITLE
Combat Walker Icons

### ISSUE THREAD

**Issue by cysterion1** [nvigneux/Helldivers-2-Stratagems-icons-svg#2]
Combat Walkers have just been added to the game, getting the svgs for those would be great! Thanks for putting these out, they are a great help!

**Comment by xKoldx** [comment]
![HD2-Walker](https://github.com/nvigneux/Helldivers-2-Stratagems-icons-svg/assets/23419821/b168471e-9bc7-44b5-b8c7-b02eeac5afcc)

**Comment by nvigneux** [comment]
yep work in progress !

**Comment by nvigneux** [comment]
thank you for the assets

**Comment by nvigneux** [comment]
Patriot exosuit is deployed !
