### ISSUE TITLE
How did you get these icon？

### ISSUE THREAD

**Issue by jd3096-mpy** [nvigneux/Helldivers-2-Stratagems-icons-svg#3]
Thank you for your contribution, and I want to learn about how did you get these icon？

**Comment by nvigneux** [comment]
You're welcome.

I often take in-game screenshots of icons or find png version on google image and vectorize them using Illustrator or Figma.
They are fairly simple shapes to replicate.

**Comment by jd3096-mpy** [comment]
> You're welcome.
> 
> I often take in-game screenshots of icons or find png version on google image and vectorize them using Illustrator or Figma. They are fairly simple shapes to replicate.

I used esp32 to make a toy for input practice.

![e9460dfbbc1430384bbcdc6bcfe6856](https://github.com/nvigneux/Helldivers-2-Stratagems-icons-svg/assets/69076780/9fa6cd98-f17f-45a7-a85e-f32340392016)

**Comment by nvigneux** [comment]
Wow, that's really cool! It's a great idea. 
I'm glad my icons could be useful for you.
