### ISSUE TITLE
Helldivers 2 collective

### ISSUE THREAD

**Issue by dealloc** [nvigneux/Helldivers-2-Stratagems-icons-svg#8]
Hey there, I'm the owner of [Helldivers 2 Community Org](https://github.com/helldivers-2).
I'd love it if you guys would consider moving into the organisation, you would maintain ownership over your repository but it would be easier for people to find the repositories if they're centralized under a single organisation that contains most handy resources available

And you guys would make a great addition!
if you'd like to discuss some details, feel free to hop on over [Discord](https://discord.gg/J38CB8s7) and ping me :)

**Comment by nvigneux** [comment]
Hey,

Thanks for the invite to join the Helldivers 2 Community ! 
It's really cool what you're doing. 
I'm interested, but I'm not quite sure what joining involves ?

I'll take some time to think about it and get back to you.

**Comment by dealloc** [comment]
it's basically moving it under `helldivers-2/icons` (or similar), it wouldn't change anything regarding ownership, licensing etc.
Essentially we try to collect the best resources for building apps/sites/etc for Helldivers 2 in one organisation.

You'd still remain full ownership over your repository, essentially just the URL would change :)
